modLoader="javafml" 
loaderVersion="[47,)" 
license="yes"

[[mods]] 
modId="velocity" 
version="1.20.1" 
displayName="Velocity"
authors="Max" 
description='''same feeling for hvh as in cs2'''

[[dependencies.velocity]] 
    modId="forge" 
    mandatory=true 
    versionRange="[47,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.velocity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"


